packages:
  # Web apps
  - 'APPS/WEB_APPS/*'
  - 'APPS/WEB_APPS/PLANAI_SUITE/*'

  # Mobile apps
  - 'APPS/MOBILE/*'

  # Concept apps
  - 'APPS/CONCEPT_APPS/*'

  # Backend services
  - 'SERVICES/*'

  # Shared packages
  - 'PACKAGES/*'

shared-workspace-lockfile: true

hoist-pattern:
  - '*'

shamefully-hoist: true
strict-peer-dependencies: false
auto-install-peers: true

node-linker: hoisted
hoist-workspace-packages: true
