name: boldmind-payment-service
type: web
runtime: node
plan: free
autoDeploy: true
buildCommand: pnpm install && pnpm build
startCommand: pnpm start
envVars:
  - key: PORT
    value: 4002
  - key: SERVICE_NAME
    value: payment-service
domains:
  - payment.boldmind.ng