name: boldmind-educenter-service
type: web
runtime: node
plan: free
autoDeploy: true
buildCommand: pnpm install && pnpm build
startCommand: pnpm start
envVars:
  - key: PORT
    value: 400
  - key: SERVICE_NAME
    value: educenter-service
domains:
  - api.educenter.com.ng