import { Module, Global } from '@nestjs/common';
import {
    UserServiceClient,
    NotificationServiceClient,
    PaymentServiceClient,
    EducenterServiceClient,
    HubServiceClient,
    AmebogistServiceClient,
    SocialFactoryServiceClient,
    EmailscraperServiceClient,
    NaijaFitherServiceClient,
    BoldmindOsServiceClient,
    SafeaiServiceClient,
    AnalyticsServiceClient,
    AiServiceClient,
    MediaServiceClient,
    AiReceptionistServiceClient,
    PlanaiSuiteServiceClient,
    NaijagigMatcherServiceClient,
    KoloAiServiceClient,
    BorderlessRemitServiceClient,
    ReceiptGeniusServiceClient,
    PowerAlertServiceClient,
    FarmgateDirectServiceClient,
    AfrocopyAiServiceClient,
    Skill2cashServiceClient,
    AnontruthMicServiceClient,
    AfrohustleOsServiceClient,
} from './index';

const clients = [
    UserServiceClient,
    NotificationServiceClient,
    PaymentServiceClient,
    EducenterServiceClient,
    HubServiceClient,
    AmebogistServiceClient,
    SocialFactoryServiceClient,
    EmailscraperServiceClient,
    NaijaFitherServiceClient,
    BoldmindOsServiceClient,
    SafeaiServiceClient,
    AnalyticsServiceClient,
    AiServiceClient,
    MediaServiceClient,
    AiReceptionistServiceClient,
    PlanaiSuiteServiceClient,
    NaijagigMatcherServiceClient,
    KoloAiServiceClient,
    BorderlessRemitServiceClient,
    ReceiptGeniusServiceClient,
    PowerAlertServiceClient,
    FarmgateDirectServiceClient,
    AfrocopyAiServiceClient,
    Skill2cashServiceClient,
    AnontruthMicServiceClient,
    AfrohustleOsServiceClient,
];

@Global()
@Module({
    providers: [...clients],
    exports: [...clients],
})
export class ClientsModule { }
