import { useState, useEffect } from "react";

const TOOLS = [
    {
        id: "emailscraper", slug: "emailscraper", name: "EmailScraper Pro", tagline: "Find verified Nigerian business emails in seconds.", icon: "🔍", status: "BUILDING", color: "#00FF87", category: "Lead Generation", subdomain: "/emailscraper",
        stat1: { n: "10,000", label: "emails/mo on Pro" }, stat2: { n: "₦5k", label: "to start" },
        description: "Scrape LinkedIn, CAC registry, VConnect, ConnectNigeria. Real-time email verification. Bulk export to CSV or CRM. Built for Nigerian B2B sales teams.",
        useCases: ["Find all Lagos real estate agents' emails", "Scrape emails of HR managers at Nigerian banks", "Build a list of food vendors in Abuja", "Find verified contacts at Nigerian tech companies"],
        pricing: [
            { tier: "Free", price: "₦0", limit: "100 emails/mo", features: ["Basic search", "Manual mode", "CSV export"] },
            { tier: "Starter", price: "₦5,000", limit: "1,000/mo", features: ["Bulk search", "Email verification", "Lead enrichment", "CRM export"] },
            { tier: "Pro", price: "₦15,000", limit: "10,000/mo", features: ["API access", "LinkedIn scraping", "Business directory scraping", "Priority support"] },
            { tier: "Enterprise", price: "₦50,000", limit: "Unlimited", features: ["White-label", "Custom integrations", "Team accounts", "SLA"] },
        ],
        features: [
            { icon: "🔗", title: "LinkedIn Discovery", desc: "Find emails from LinkedIn profiles without paying LinkedIn Premium" },
            { icon: "🏢", title: "Nigerian Directories", desc: "CAC registry, VConnect, ConnectNigeria — scraped and indexed daily" },
            { icon: "✅", title: "Real-time Verification", desc: "MX record + SMTP check. 94% accuracy rate guaranteed" },
            { icon: "📊", title: "Lead Enrichment", desc: "Company, role, phone number appended automatically to every result" },
            { icon: "⚡", title: "Bulk Operations", desc: "Upload 500 company names, get all contacts back in minutes" },
            { icon: "🔌", title: "API Access", desc: "Integrate email discovery directly into your sales workflow" },
        ],
    },
    {
        id: "social-factory", slug: "social", name: "Social Content Factory", tagline: "AI content for 6 platforms. Schedule once. Post everywhere.", icon: "🎬", status: "BUILDING", color: "#FF6B35", category: "Content Automation", subdomain: "/social",
        stat1: { n: "6", label: "platforms in 1" }, stat2: { n: "30 posts", label: "in one session" },
        description: "AI caption generator trained on Nigerian market context. Content calendar with drag-and-drop. Auto-schedule to Instagram, TikTok, Facebook, X, LinkedIn, YouTube.",
        useCases: ["Schedule 30 posts across all platforms in 20 minutes", "Generate Nigerian-market captions that actually convert", "Turn one blog post into 10 different social posts automatically", "Nigerian trending topics → auto-suggested content ideas"],
        pricing: [
            { tier: "Free", price: "₦0", limit: "5 posts/mo", features: ["2 accounts", "Basic templates", "Manual publish"] },
            { tier: "Starter", price: "₦10,000", limit: "50 posts/mo", features: ["5 accounts", "AI captions", "Scheduling", "Analytics"] },
            { tier: "Pro", price: "₦25,000", limit: "200 posts/mo", features: ["Unlimited accounts", "AI image gen", "Bulk creation", "Advanced analytics"] },
            { tier: "Agency", price: "₦50,000", limit: "Unlimited", features: ["White-label", "Client management", "API access", "Priority support"] },
        ],
        features: [
            { icon: "🤖", title: "Nigerian AI Captions", desc: "Brand voice training + one-click Pidgin English mode" },
            { icon: "📅", title: "Drag-Drop Calendar", desc: "Visual content calendar — see your entire month at a glance" },
            { icon: "🌍", title: "6 Platforms", desc: "Instagram, TikTok, Facebook, X, LinkedIn, YouTube — all in one" },
            { icon: "🎨", title: "AI Image Generation", desc: "Post graphics generated by fal.ai FLUX model on demand" },
            { icon: "📈", title: "Best Time Analytics", desc: "Know exactly when your Nigerian audience is most active" },
            { icon: "♻️", title: "Content Repurpose", desc: "1 blog post or video → 10 unique social posts automatically" },
        ],
    },
];

function Demo({ tool }) {
    const [input, setInput] = useState("");
    const [result, setResult] = useState(null);
    const [scanning, setScanning] = useState(false);

    const run = () => {
        if (!input.trim()) return;
        setScanning(true); setResult(null);
        setTimeout(() => {
            if (tool.id === "emailscraper") {
                setResult({
                    type: "emails", found: Math.floor(Math.random() * 40) + 15, verified: Math.floor(Math.random() * 30) + 10,
                    sample: [
                        { email: `contact@${input.toLowerCase().replace(/\s/g, "")}.com.ng`, score: 94, role: "MD/CEO", ok: true },
                        { email: `sales@${input.toLowerCase().replace(/\s/g, "")}.ng`, score: 87, role: "Sales Manager", ok: true },
                        { email: `info@${input.toLowerCase().replace(/\s/g, "")}.ng`, score: 72, role: "General Inquiry", ok: false },
                    ]
                });
            } else {
                setResult({
                    type: "captions", items: [
                        { platform: "Instagram 📸", text: `🔥 Big news for ${input}! We dey bring you something wey go change your life fr fr. Drop a 🙌 if you ready!\n\n#Nigeria #${input.replace(/\s/g, "")} #BoldMind` },
                        { platform: "Twitter/X 🐦", text: `Your ${input} journey just got easier. We built the tool you've been waiting for.\n\nThread below 👇` },
                        { platform: "LinkedIn 💼", text: `Excited to share a major update for ${input}.\n\nAfter months of focused building, we're ready to reveal what we've created...` },
                    ]
                });
            }
            setScanning(false);
        }, 1600);
    };

    return (
        <div style={{ padding: "24px 28px", background: "rgba(0,0,0,0.5)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 18 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 16 }}>
                <span style={{ width: 7, height: 7, borderRadius: "50%", background: tool.color, boxShadow: `0 0 8px ${tool.color}`, display: "inline-block" }} />
                <span style={{ fontFamily: "'Space Mono', monospace", fontSize: 10, color: tool.color, letterSpacing: "0.18em" }}>
                    LIVE DEMO — {tool.id === "emailscraper" ? "ENTER COMPANY / INDUSTRY" : "ENTER YOUR PRODUCT OR BRAND"}
                </span>
            </div>
            <div style={{ fontFamily: "'Space Mono', monospace", fontSize: 12, color: "rgba(245,240,232,0.25)", marginBottom: 10 }}>
                {tool.id === "emailscraper" ? `$ boldmind email search --company="..."` : `$ boldmind social generate --topic="..."`}
            </div>
            <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
                <input value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === "Enter" && run()}
                    placeholder={tool.id === "emailscraper" ? `e.g. "GTBank" or "Lagos Tech Startups"` : `e.g. "fashion brand in Lagos"`}
                    style={{ flex: 1, background: "rgba(255,255,255,0.05)", border: `1px solid ${tool.color}30`, borderRadius: 8, padding: "10px 14px", color: "#F5F0E8", fontSize: 12, outline: "none", fontFamily: "'Space Mono', monospace" }} />
                <button onClick={run} disabled={scanning} style={{ padding: "10px 20px", background: tool.color, border: "none", borderRadius: 8, color: "#080808", fontFamily: "'Space Grotesk', sans-serif", fontWeight: 800, fontSize: 12, cursor: "pointer", letterSpacing: "0.08em", whiteSpace: "nowrap" }}>
                    {scanning ? "..." : "RUN →"}
                </button>
            </div>
            {result && (
                <div style={{ animation: "fadein 0.3s ease-out" }}>
                    {result.type === "emails" ? (
                        <>
                            <div style={{ display: "flex", gap: 12, marginBottom: 12 }}>
                                {[{ n: result.found, label: "EMAILS FOUND", c: tool.color }, { n: result.verified, label: "VERIFIED", c: "#22C55E" }].map(s => (
                                    <div key={s.label} style={{ flex: 1, padding: "12px 14px", background: `${s.c}10`, border: `1px solid ${s.c}30`, borderRadius: 10, textAlign: "center" }}>
                                        <div style={{ fontSize: 26, fontWeight: 800, color: s.c, fontFamily: "'Space Grotesk', sans-serif" }}>{s.n}</div>
                                        <div style={{ fontSize: 9, color: "rgba(245,240,232,0.35)", fontFamily: "'Space Mono', monospace", letterSpacing: "0.12em" }}>{s.label}</div>
                                    </div>
                                ))}
                            </div>
                            {result.sample.map((r, i) => (
                                <div key={i} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "8px 12px", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 8, marginBottom: 6 }}>
                                    <span style={{ fontFamily: "'Space Mono', monospace", fontSize: 12, color: "#F5F0E8" }}>{r.email} <span style={{ color: "rgba(245,240,232,0.3)" }}>· {r.role}</span></span>
                                    <div style={{ display: "flex", gap: 10 }}>
                                        <span style={{ fontSize: 11, color: tool.color, fontFamily: "'Space Mono', monospace" }}>{r.score}%</span>
                                        <span style={{ fontSize: 11, color: r.ok ? "#22C55E" : "#F59E0B" }}>{r.ok ? "✓ OK" : "⚠ CHECK"}</span>
                                    </div>
                                </div>
                            ))}
                            <p style={{ fontFamily: "'Space Mono', monospace", fontSize: 10, color: "rgba(245,240,232,0.2)", marginTop: 10 }}>// Demo only — sign up to export all {result.found} emails</p>
                        </>
                    ) : (
                        <>
                            {result.items.map((c, i) => (
                                <div key={i} style={{ padding: "12px 14px", background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 10, marginBottom: 8 }}>
                                    <div style={{ fontSize: 11, color: tool.color, fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, letterSpacing: "0.1em", marginBottom: 6 }}>{c.platform}</div>
                                    <p style={{ fontFamily: "'Space Mono', monospace", fontSize: 11, color: "rgba(245,240,232,0.6)", lineHeight: 1.6, margin: 0, whiteSpace: "pre-line" }}>{c.text}</p>
                                </div>
                            ))}
                            <p style={{ fontFamily: "'Space Mono', monospace", fontSize: 10, color: "rgba(245,240,232,0.2)", marginTop: 6 }}>// Sign up to schedule these to all 6 platforms instantly</p>
                        </>
                    )}
                </div>
            )}
        </div>
    );
}

export default function ToolsLanding() {
    const [active, setActive] = useState(TOOLS[0]);
    const [tab, setTab] = useState("overview");

    useEffect(() => { setTab("overview"); }, [active.id]);

    return (
        <div style={{ background: "#080808", color: "#F5F0E8", minHeight: "100vh", fontFamily: "'DM Sans', sans-serif", overflowX: "hidden" }}>
            <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;700;800&family=DM+Sans:opsz,wght@9..40,300;9..40,400;9..40,600&family=Space+Mono:wght@400;700&display=swap');
        .sg{font-family:'Space Grotesk',sans-serif} .mono{font-family:'Space Mono',monospace}
        @keyframes fadein{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
        @keyframes scan{0%{top:-2%}100%{top:102%}}
        .fadein{animation:fadein 0.55s ease-out forwards}
        .hov:hover{background:rgba(255,255,255,0.05)!important;transform:translateX(3px)}
        ::-webkit-scrollbar{width:3px} ::-webkit-scrollbar-track{background:#080808} ::-webkit-scrollbar-thumb{background:rgba(255,255,255,0.12)}
        input::placeholder{color:rgba(245,240,232,0.2)}
      `}</style>

            {/* Scan FX */}
            <div style={{ position: "fixed", inset: 0, pointerEvents: "none", zIndex: 900, overflow: "hidden" }}>
                <div style={{ position: "absolute", left: 0, right: 0, height: 2, background: `linear-gradient(90deg,transparent,${active.color}12,transparent)`, animation: "scan 7s linear infinite" }} />
                <div style={{ position: "absolute", inset: 0, backgroundImage: "repeating-linear-gradient(0deg,rgba(255,255,255,0.007) 0px,rgba(255,255,255,0.007) 1px,transparent 1px,transparent 4px)" }} />
            </div>
            <div style={{ position: "fixed", top: "15%", right: "-5%", width: 450, height: 450, background: `radial-gradient(circle,${active.color}07 0%,transparent 65%)`, transition: "background 0.5s", pointerEvents: "none", zIndex: 0 }} />

            {/* NAV */}
            <nav style={{ position: "fixed", top: 0, left: 0, right: 0, zIndex: 200, height: 60, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 48px", background: "rgba(8,8,8,0.9)", backdropFilter: "blur(14px)", borderBottom: "1px solid rgba(255,255,255,0.07)" }}>
                <a href="https://boldmind.ng" style={{ display: "flex", alignItems: "center", gap: 8, textDecoration: "none" }}>
                    <span className="sg" style={{ color: "#F5F0E8", fontWeight: 800, fontSize: 15 }}>🛠 BoldMind</span>
                    <span style={{ color: "rgba(245,240,232,0.2)" }}>/</span>
                    <span className="sg" style={{ color: active.color, fontWeight: 700, fontSize: 15, transition: "color 0.3s" }}>Tools</span>
                </a>
                <div style={{ display: "flex", gap: 4 }}>
                    {["EmailScraper", "Social Factory", "Pricing", "Docs"].map(l => (
                        <a key={l} href="#" style={{ padding: "5px 12px", color: "rgba(245,240,232,0.35)", fontSize: 13, fontWeight: 500, textDecoration: "none", borderRadius: 6 }}
                            onMouseEnter={e => e.currentTarget.style.color = "#F5F0E8"} onMouseLeave={e => e.currentTarget.style.color = "rgba(245,240,232,0.35)"}>{l}</a>
                    ))}
                </div>
                <div style={{ display: "flex", gap: 8 }}>
                    <a href="https://boldmind.ng/login" style={{ padding: "8px 16px", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 8, color: "rgba(245,240,232,0.55)", fontSize: 13, fontWeight: 600, textDecoration: "none" }}>Sign in</a>
                    <a href="https://boldmind.ng/register?redirect=https://tools.boldmind.ng" style={{ padding: "8px 18px", background: active.color, borderRadius: 8, color: "#080808", fontSize: 13, fontWeight: 800, textDecoration: "none", transition: "background 0.3s" }}>Join Waitlist →</a>
                </div>
            </nav>

            {/* HERO */}
            <section style={{ minHeight: "92vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "80px 48px 60px", textAlign: "center", position: "relative" }}>
                <div style={{ position: "absolute", inset: 0, backgroundImage: "linear-gradient(rgba(255,255,255,0.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,0.025) 1px,transparent 1px)", backgroundSize: "40px 40px", pointerEvents: "none" }} />

                <div className="fadein" style={{ display: "inline-flex", alignItems: "center", gap: 8, padding: "5px 14px", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 6, background: "rgba(255,255,255,0.03)", marginBottom: 28 }}>
                    <span className="mono" style={{ fontSize: 10, color: "rgba(245,240,232,0.4)", letterSpacing: "0.18em" }}>tools.boldmind.ng</span>
                    <span style={{ color: "rgba(245,240,232,0.15)" }}>·</span>
                    <span className="mono" style={{ fontSize: 10, color: "#FFC800", letterSpacing: "0.15em" }}>2 TOOLS · BUILDING</span>
                </div>

                <h1 className="sg fadein" style={{ fontSize: "clamp(52px, 9vw, 108px)", fontWeight: 800, lineHeight: 0.92, letterSpacing: "-0.035em", marginBottom: 24, animationDelay: "0.1s" }}>
                    B2B Tools<br />
                    <span style={{ color: active.color, transition: "color 0.3s" }}>Built for</span><br />
                    <span style={{ WebkitTextStroke: "2px rgba(245,240,232,0.25)", color: "transparent" }}>Nigeria.</span>
                </h1>

                <p className="fadein" style={{ color: "rgba(245,240,232,0.4)", fontSize: "clamp(14px, 1.8vw, 17px)", maxWidth: 480, lineHeight: 1.75, marginBottom: 44, animationDelay: "0.2s", fontWeight: 300 }}>
                    EmailScraper Pro finds verified business contacts from Nigerian directories.<br />
                    Social Content Factory schedules AI-generated content to 6 platforms.<br />
                    Both built by Nigerians, for Nigerians.
                </p>

                <div className="fadein" style={{ display: "flex", gap: 10, animationDelay: "0.3s", marginBottom: 52 }}>
                    {TOOLS.map(t => (
                        <button key={t.id} onClick={() => setActive(t)} style={{ padding: "12px 28px", background: active.id === t.id ? t.color : "rgba(255,255,255,0.04)", border: `1px solid ${active.id === t.id ? t.color : "rgba(255,255,255,0.1)"}`, borderRadius: 10, color: active.id === t.id ? "#080808" : "rgba(245,240,232,0.55)", fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 14, cursor: "pointer", transition: "all 0.2s", display: "flex", alignItems: "center", gap: 8 }}>
                            {t.icon} {t.name}
                        </button>
                    ))}
                </div>

                <div className="fadein" style={{ display: "flex", gap: 36, animationDelay: "0.4s" }}>
                    {[{ n: "4 tiers", l: "Free → Enterprise" }, { n: "100%", l: "Nigerian-built" }, { n: "Q2 2026", l: "Launch target" }].map(({ n, l }) => (
                        <div key={l} style={{ textAlign: "center" }}>
                            <div className="sg" style={{ fontSize: 30, fontWeight: 800, color: active.color, transition: "color 0.3s" }}>{n}</div>
                            <div className="mono" style={{ fontSize: 9, color: "rgba(245,240,232,0.28)", letterSpacing: "0.15em", textTransform: "uppercase", marginTop: 4 }}>{l}</div>
                        </div>
                    ))}
                </div>
            </section>

            {/* TOOL DEEP DIVE */}
            <section style={{ padding: "60px 48px", borderTop: "1px solid rgba(255,255,255,0.06)" }}>
                <div style={{ maxWidth: 1100, margin: "0 auto", display: "grid", gridTemplateColumns: "240px 1fr", gap: 24 }}>
                    {/* Sidebar */}
                    <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
                        <p className="mono" style={{ fontSize: 9, color: "rgba(245,240,232,0.25)", letterSpacing: "0.2em", marginBottom: 4 }}>// SELECT TOOL</p>
                        {TOOLS.map(t => (
                            <button key={t.id} onClick={() => setActive(t)} style={{ padding: "16px 18px", background: active.id === t.id ? `${t.color}10` : "rgba(255,255,255,0.02)", border: `1px solid ${active.id === t.id ? t.color + "50" : "rgba(255,255,255,0.07)"}`, borderRadius: 14, cursor: "pointer", textAlign: "left", transition: "all 0.2s", width: "100%" }}>
                                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 6 }}>
                                    <span style={{ fontSize: 22 }}>{t.icon}</span>
                                    <span style={{ fontSize: 9, padding: "2px 7px", background: "rgba(255,200,0,0.1)", color: "#FFC800", border: "1px solid rgba(255,200,0,0.25)", borderRadius: 20, fontWeight: 800, letterSpacing: "0.15em", alignSelf: "flex-start" }}>BUILDING</span>
                                </div>
                                <div className="sg" style={{ fontWeight: 800, fontSize: 13, color: active.id === t.id ? "#F5F0E8" : "rgba(245,240,232,0.6)", marginBottom: 2 }}>{t.name}</div>
                                <div className="mono" style={{ fontSize: 10, color: "rgba(245,240,232,0.3)" }}>{t.category}</div>
                            </button>
                        ))}
                        <div style={{ marginTop: 14, padding: "16px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 12 }}>
                            <p className="mono" style={{ fontSize: 9, color: "rgba(245,240,232,0.25)", letterSpacing: "0.15em", marginBottom: 10 }}>// ECOSYSTEM LINKS</p>
                            {[["🚀", "BoldMind Hub", "boldmind.ng"], ["🤖", "PlanAI", "planai.boldmind.ng"], ["🎓", "EduCenter", "educenter.com.ng"], ["📰", "AmeboGist", "amebogist.ng"]].map(([icon, name, url]) => (
                                <a key={url} href={`https://${url}`} style={{ display: "flex", gap: 8, padding: "7px 0", textDecoration: "none", borderBottom: "1px solid rgba(255,255,255,0.04)" }}>
                                    <span style={{ fontSize: 13 }}>{icon}</span>
                                    <div>
                                        <div style={{ fontSize: 12, color: "rgba(245,240,232,0.65)", fontWeight: 600 }}>{name}</div>
                                        <div className="mono" style={{ fontSize: 9, color: "rgba(245,240,232,0.2)" }}>{url}</div>
                                    </div>
                                </a>
                            ))}
                        </div>
                    </div>

                    {/* Main */}
                    <div key={active.id} style={{ animation: "fadein 0.3s ease-out" }}>
                        <div style={{ padding: "24px 28px", background: `${active.color}08`, border: `1px solid ${active.color}30`, borderRadius: 18, marginBottom: 18 }}>
                            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 20 }}>
                                <div>
                                    <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 6 }}>
                                        <span style={{ fontSize: 32 }}>{active.icon}</span>
                                        <div>
                                            <h2 className="sg" style={{ fontSize: 26, fontWeight: 800, margin: 0 }}>{active.name}</h2>
                                            <p className="mono" style={{ fontSize: 10, color: active.color, margin: "3px 0 0", letterSpacing: "0.1em" }}>tools.boldmind.ng{active.subdomain}</p>
                                        </div>
                                    </div>
                                    <p style={{ color: "rgba(245,240,232,0.55)", fontSize: 15, maxWidth: 480, lineHeight: 1.65, margin: 0, fontWeight: 300 }}>{active.description}</p>
                                </div>
                                <div style={{ display: "flex", gap: 14, flexShrink: 0 }}>
                                    {[active.stat1, active.stat2].map(s => (
                                        <div key={s.label} style={{ padding: "12px 16px", background: "rgba(0,0,0,0.4)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: 10, textAlign: "center" }}>
                                            <div className="sg" style={{ fontSize: 20, fontWeight: 800, color: active.color }}>{s.n}</div>
                                            <div className="mono" style={{ fontSize: 8, color: "rgba(245,240,232,0.3)", letterSpacing: "0.12em", textTransform: "uppercase", marginTop: 3 }}>{s.label}</div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                            <div style={{ display: "flex", gap: 6 }}>
                                {["overview", "demo", "pricing"].map(t => (
                                    <button key={t} onClick={() => setTab(t)} style={{ padding: "6px 16px", background: tab === t ? active.color : "rgba(0,0,0,0.35)", border: `1px solid ${tab === t ? active.color : "rgba(255,255,255,0.1)"}`, borderRadius: 7, color: tab === t ? "#080808" : "rgba(245,240,232,0.45)", fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 11, cursor: "pointer", textTransform: "uppercase", letterSpacing: "0.1em", transition: "all 0.15s" }}>
                                        {t}
                                    </button>
                                ))}
                            </div>
                        </div>

                        {tab === "overview" && (
                            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
                                {active.features.map(f => (
                                    <div key={f.title} className="hov" style={{ padding: "16px 18px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 14, transition: "all 0.15s" }}>
                                        <div style={{ display: "flex", gap: 10 }}>
                                            <span style={{ fontSize: 20, flexShrink: 0 }}>{f.icon}</span>
                                            <div>
                                                <div className="sg" style={{ fontWeight: 700, fontSize: 14, marginBottom: 3 }}>{f.title}</div>
                                                <p style={{ fontSize: 13, color: "rgba(245,240,232,0.42)", margin: 0, lineHeight: 1.5, fontWeight: 300 }}>{f.desc}</p>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}

                        {tab === "demo" && <Demo tool={active} />}

                        {tab === "pricing" && (
                            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10 }}>
                                {active.pricing.map((p, i) => (
                                    <div key={p.tier} style={{ padding: "20px 16px", background: i === 2 ? `${active.color}08` : "rgba(255,255,255,0.02)", border: `1px solid ${i === 2 ? active.color + "40" : "rgba(255,255,255,0.07)"}`, borderRadius: 14, transition: "all 0.2s" }}>
                                        {i === 2 && <div style={{ background: active.color, color: "#080808", fontSize: 8, fontWeight: 800, letterSpacing: "0.15em", padding: "2px 8px", borderRadius: 20, width: "fit-content", marginBottom: 8 }}>POPULAR</div>}
                                        <div className="sg" style={{ fontSize: 14, fontWeight: 800, marginBottom: 3 }}>{p.tier}</div>
                                        <div className="sg" style={{ fontSize: 22, fontWeight: 800, color: i === 2 ? active.color : "#F5F0E8", marginBottom: 2 }}>{p.price}</div>
                                        <div className="mono" style={{ fontSize: 9, color: "rgba(245,240,232,0.3)", letterSpacing: "0.1em", marginBottom: 14 }}>{p.limit}</div>
                                        {p.features.map(f => (
                                            <div key={f} style={{ display: "flex", gap: 6, alignItems: "flex-start", marginBottom: 6 }}>
                                                <span style={{ color: active.color, fontSize: 11, flexShrink: 0 }}>✓</span>
                                                <span style={{ fontSize: 11, color: "rgba(245,240,232,0.5)", lineHeight: 1.4 }}>{f}</span>
                                            </div>
                                        ))}
                                        <button onClick={() => window.location.href = `https://boldmind.ng/register?redirect=https://tools.boldmind.ng${active.subdomain}&tier=${p.tier.toLowerCase()}`}
                                            style={{ width: "100%", marginTop: 14, padding: "9px", background: i === 2 ? active.color : "rgba(255,255,255,0.05)", border: `1px solid ${i === 2 ? active.color : "rgba(255,255,255,0.1)"}`, borderRadius: 7, color: i === 2 ? "#080808" : "rgba(245,240,232,0.6)", fontFamily: "'Space Grotesk', sans-serif", fontWeight: 700, fontSize: 11, cursor: "pointer", transition: "all 0.15s" }}>
                                            {p.price === "₦0" ? "Start Free" : "Join Waitlist"}
                                        </button>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                </div>
            </section>

            {/* USE CASES */}
            <section style={{ padding: "60px 48px", borderTop: "1px solid rgba(255,255,255,0.06)", textAlign: "center" }}>
                <div style={{ maxWidth: 800, margin: "0 auto" }}>
                    <h2 className="sg" style={{ fontSize: 28, fontWeight: 800, marginBottom: 28 }}>What <span style={{ color: active.color }}>{active.name}</span> Is Built For</h2>
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
                        {active.useCases.map((uc, i) => (
                            <div key={i} style={{ display: "flex", gap: 10, padding: "14px 16px", background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 10, textAlign: "left" }}>
                                <span className="mono" style={{ color: active.color, fontSize: 12, flexShrink: 0 }}>→</span>
                                <span style={{ fontSize: 13, color: "rgba(245,240,232,0.6)", lineHeight: 1.5 }}>{uc}</span>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* CTA */}
            <section style={{ padding: "60px 48px 80px", textAlign: "center" }}>
                <div style={{ maxWidth: 560, margin: "0 auto" }}>
                    <h2 className="sg" style={{ fontSize: 38, fontWeight: 800, marginBottom: 14 }}>Founding member <span style={{ color: active.color }}>benefits.</span></h2>
                    <p style={{ color: "rgba(245,240,232,0.4)", marginBottom: 32, fontSize: 16, fontWeight: 300 }}>Both tools launch Q2 2026. Founding members get 3 months free on any paid tier.</p>
                    <div style={{ display: "flex", gap: 10, justifyContent: "center" }}>
                        <a href="https://boldmind.ng/register?redirect=https://tools.boldmind.ng&source=cta" style={{ padding: "15px 32px", background: active.color, borderRadius: 10, color: "#080808", fontFamily: "'Space Grotesk', sans-serif", fontWeight: 800, fontSize: 15, textDecoration: "none", transition: "background 0.3s" }}>Join Waitlist Free →</a>
                        <a href="https://boldmind.ng" style={{ padding: "15px 24px", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 10, color: "rgba(245,240,232,0.55)", fontFamily: "'Space Grotesk', sans-serif", fontWeight: 600, fontSize: 15, textDecoration: "none" }}>Explore Ecosystem</a>
                    </div>
                    <p className="mono" style={{ marginTop: 18, fontSize: 10, color: "rgba(245,240,232,0.18)" }}>// tools.boldmind.ng · Part of the 32-product BoldMind ecosystem</p>
                </div>
            </section>
        </div>
    );
}